version: '3.3'
services:
    portainer-ce:
        ports:
            - '9000:9000'
            - '9443:9443'
            - '8000:8000'
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        image: 'portainer/portainer-ce:linux-arm'

    qbittorrent:
        build:
            context: .
            dockerfile: Qbittorrent.Dockerfile
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - WEBUI_PORT=4591
        ports:
            - 4591:4591
            - 6881:6881
            - 6881:6881/udp
        volumes:
            - primary:/A
            - secondary:/B
            - /home/zireael9797/qBittorrentConfig:/config:z
        command: ["/bin/bash", "-c", "sleep 5 && chmod -R 777 /A && chmod -R 777 /B && qbittorrent-nox"] #Figure this out
        restart: unless-stopped

    samba:
        image: dperson/samba
        container_name: samba
        environment:
            TZ: 'EST5EDT'
        networks:
            - default
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        read_only: false
        tmpfs:
            - /tmp
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - primary:/A
            - secondary:/B
        command: '-s "A;/A;yes;no;yes;;zireael9797;zireael9797;globalshare" -s "B;/B;yes;no;yes;;zireael9797;zireael9797;globalshare" -u "zireael9797;ageraone1" -p'

    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        user: "{UID}:{GID}"
        ports:
        - "9090:8080"
        volumes:
        - primary:/srv/a
        - secondary:/srv/b
        - ~/filebrowser/filebrowser.db:/database/filebrowser.db
        restart: always

networks:
    default:


volumes:
    portainer_data:
        name: portainer_data
        external: false
    primary:
        driver: local
        driver_opts:
            device: /dev/disk/by-uuid/05ac0341-38f1-489b-b054-4a4f811d1537
            type: ext4
    secondary:
        driver: local
        driver_opts:
            device: /dev/disk/by-uuid/57568cb7-8818-4c66-b7c2-d62b5bccba0e
            type: ext4
